In [2]:
print("Sample 2")

Sample 2


In [3]:
import numpy as np

In [5]:
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
a2=np.array([[1,1,1],[1,1,1],[1,1,1]])
print(a1+a2)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [7]:
print(a1.shape)

(3, 3)


In [9]:
print((a1+a2).shape)

(3, 3)


In [12]:
a3=np.array([[1,2,3],[4,5,6]])
print(a3)
print(a3.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [13]:
for i in range(len(a3)):
    for j in range(len(a3[0])):
        if i == n:
            print(a3[i][j])
            
    

1
5


In [19]:
ar1=np.array([[1,1,1],[2,2,2],[3,3,3]])
ar2=np.array([[1,2,3],[1,2,3],[1,2,3]])
ar3=np.matmul(ar1,ar2)
print(ar3)

[[ 3  6  9]
 [ 6 12 18]
 [ 9 18 27]]


In [22]:
print(np.sum(ar3))
print(np.sum(ar1))

108
18


In [97]:
print(np.sum(ar3[1]))

36


In [99]:
#random matrix with dimension given in ()
b=np.random.rand(3,4,2)
print(b)

[[[0.75245994 0.20695756]
  [0.94780147 0.950846  ]
  [0.88258407 0.19117781]
  [0.13395626 0.68124064]]

 [[0.71506318 0.30893842]
  [0.86779661 0.20938335]
  [0.38315998 0.19008053]
  [0.75872126 0.989748  ]]

 [[0.46231058 0.29503068]
  [0.72094888 0.74866868]
  [0.47729167 0.86494642]
  [0.3546864  0.25945596]]]


In [45]:
b = np.random.rand(3,3,2)
a=np.random.rand(3,2,3)
print(np.dot(a,b))
print("----------------")
print(np.matmul(a,b))

[[[[0.75165074 0.82853674]
   [0.43437929 0.84472934]
   [0.48021252 0.67900969]]

  [[1.60099262 1.6872776 ]
   [1.24169383 1.846065  ]
   [1.23875409 1.60921025]]]


 [[[0.8221844  0.76899113]
   [0.74416274 0.91776709]
   [0.70571709 0.83692633]]

  [[1.07240275 0.94850849]
   [0.81312973 1.11380259]
   [0.80899774 0.95280775]]]


 [[[1.06306718 0.84141431]
   [0.90005873 1.06915742]
   [0.86280444 0.94588305]]

  [[0.27721004 0.36922452]
   [0.30751927 0.39758881]
   [0.28193412 0.38812455]]]]
----------------
[[[0.75165074 0.82853674]
  [1.60099262 1.6872776 ]]

 [[0.74416274 0.91776709]
  [0.81312973 1.11380259]]

 [[0.86280444 0.94588305]
  [0.28193412 0.38812455]]]


In [46]:
q=np.array([2,2,2])


In [47]:
print(np.mean(q))

2.0


In [48]:
print(np.exp(5))

148.4131591025766


In [53]:
#flattening an array
a=np.array([[1,2,3],[5,6,7],["m","m","m"]])
v=np.ndarray.flatten(a)
print(v)
print(v.shape)


['1' '2' '3' '5' '6' '7' 'm' 'm' 'm']
(9,)


In [58]:
print(np.arange(5,15,2))

[ 5  7  9 11 13]


In [64]:
a=np.arange(1,12,2)
print(a)

[ 1  3  5  7  9 11]


In [70]:
a2d=a.reshape(2,3)
print(a2d)

[[ 1  3  5]
 [ 7  9 11]]


In [71]:
np.sort(a)

array([ 1,  3,  5,  7,  9, 11])

In [86]:
arr=np.array([1,2,3,-4,5,-6,7])
print(np.max(arr))
print(np.min(arr))
print(np.abs(arr))
np.sort(arr)

7
-6
[1 2 3 4 5 6 7]


array([-6, -4,  1,  2,  3,  5,  7])

In [100]:
print(np.zeros((3,2)))
print("---------------")
print(np.ones((3,2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]
---------------
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [101]:
#array of n-dimension with same value
print(np.full((4,4),fill_value=3))

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [79]:
#identity matrix
print(np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [84]:
ar=np.array([[1],[2],[3]])
print(np.squeeze(ar))

[1 2 3]


In [87]:
print(arr)

[ 1  2  3 -4  5 -6  7]


In [91]:
a=np.sort(arr)
print(np.argmax(arr))
print(np.argmin(arr))
print(a)

6
5
[-6 -4  1  2  3  5  7]


In [92]:
print(np.argwhere(arr))

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [96]:
random_arr=np.random.rand(2,3)
print(random_arr)

[[0.68564682 0.2674864  0.46169718]
 [0.01644922 0.3558263  0.34053813]]


In [ ]:
print(random_arr)