In [3]:
print("Hello")
print("hiii")
print(6+9)

Hello
hiii
15


In [5]:
import numpy as np

In [6]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr_1d)

# Creating a 2D NumPy array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D Array:")
print(arr_2d)

1D Array:
[1 2 3 4 5]

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print("\nArray Operations:")
print("Sum of 1D array:", np.sum(arr_1d))
print("Mean of 2D array:", np.mean(arr_2d))
print("Transposed 2D array:")
print(np.transpose(arr_2d))


Array Operations:
Sum of 1D array: 15
Mean of 2D array: 5.0
Transposed 2D array:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [9]:
import pandas as pd
print(pd)

<module 'pandas' from 'C:\\Users\\91907\\anaconda3\\Lib\\site-packages\\pandas\\__init__.py'>


In [ ]:
def 